allowBuilds:
  '@clerk/shared': true
  '@heroui/shared-utils': true
  '@sentry/cli': true
  '@tsparticles/engine': true
  core-js: true
  esbuild: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - '@heroui/shared-utils'
  - '@tsparticles/engine'
  - sharp
  - unrs-resolver
